name: Azan Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Azan Bot
        env:
          TUYA_ACCESS_ID: ${{ secrets.TUYA_ACCESS_ID }}
          TUYA_ACCESS_SECRET: ${{ secrets.TUYA_ACCESS_SECRET }}
          TUYA_DEVICE_ID: ${{ secrets.TUYA_DEVICE_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
